<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tim Kurfiss">
<meta name="author" content="Tom Freudenmann">

<title>Untersuchung der Gehälter von Cyber-Security Experten</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="research_cyber_salaries_files/libs/clipboard/clipboard.min.js"></script>
<script src="research_cyber_salaries_files/libs/quarto-html/quarto.js"></script>
<script src="research_cyber_salaries_files/libs/quarto-html/popper.min.js"></script>
<script src="research_cyber_salaries_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="research_cyber_salaries_files/libs/quarto-html/anchor.min.js"></script>
<link href="research_cyber_salaries_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="research_cyber_salaries_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="research_cyber_salaries_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="research_cyber_salaries_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="research_cyber_salaries_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Untersuchung der Gehälter von Cyber-Security Experten</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor:innen</div>
    <div class="quarto-title-meta-contents">
             <p>Tim Kurfiss </p>
             <p>Tom Freudenmann </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Veröffentlichungsdatum</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2. Januar 2023</p>
    </div>
  </div>
    
  </div>
  

</header>

<div class="cell">

</div>
<section id="formulierung-der-fragestellung" class="level2">
<h2 class="anchored" data-anchor-id="formulierung-der-fragestellung">1. Formulierung der Fragestellung</h2>
<p>Der vorligende Datensatz enthält Daten über die Jahresgehälter von verschiedenen Angeställten im Bereich Cyber-Security und werden unter folgendem Link <a href="https://www.kaggle.com/datasets/whenamancodes/infoseccyber-security-salaries" class="uri">https://www.kaggle.com/datasets/whenamancodes/infoseccyber-security-salaries</a> bereitgestellt. Der Datensatz enthält folgende Informationen:</p>
<ul>
<li>Arbeitsjahr</li>
<li>Jobtitel</li>
<li>Erfahrungslevel</li>
<li>Job Status</li>
<li>Jahresgehalt in US-Dollar und anderen Währungen</li>
<li>Wohnort des Mitarbeiters</li>
<li>Betriebsstandort</li>
<li>Betriebsgröße</li>
<li>Remote Anteil an der Arbeit</li>
</ul>
<section id="interesse-an-den-daten" class="level3">
<h3 class="anchored" data-anchor-id="interesse-an-den-daten">1.1 Interesse an den Daten</h3>
<p>Dadurch, dass immer mehr Prozesse in Unternehmen digitalisiert werden, steigt auch die Gefahr von Cyber-Angriffen. Um diese Gefahr abzuwehren, werden immer mehr Cyber-Security Experten benötigt. Diese Experten sind in der Lage, die Sicherheit von Unternehmen zu gewährleisten. In dieser Arbeit sollen dafür die Gehälter von verschiedenen Cyber-Security Bereichen untersucht werden, um einen Einblick in die Nachfrage von Cyber-Security Experten zu bekommen. Zudem können die Ergebnisse der Arbeit dazu genutzt werden, um die Gehälter von Cyber-Security Experten zu vergleichen und zu bewerten.</p>
</section>
<section id="fragestellung" class="level3">
<h3 class="anchored" data-anchor-id="fragestellung">1.2 Fragestellung</h3>
<p>Die übergeordnete Fragestellung liegt darin, herrauszufinden welche Faktoren von der Bezahlung eines Cyber-Security Experten abhängen. Dabei sind die einzelnen Faktoren miteinander zu vergleichen und mögliche Korrelationen aufzudecken.</p>
<p>Innerhalb des Cyber-Security Bereichs existieren zudem viele unterschiedliche Titel die auf den genaueren Einsatzbereich des Angestellen schließen können. Hier können möglicherweise einzelne Gruppen gebildet werden, die ebenfalls einen gewissen Einfluss auf das Gehalt eines Mitarbeiters haben.</p>
<p>Abgesehen davon könnte sich auch die Fragestellung ergeben, ob sich die Gehälter von Cyber-Security Experten über die Zeit verändert haben. Hierbei ist zu untersuchen, wo und durch welche Faktoren sich die Gehälter verändert haben.</p>
</section>
<section id="erwartete-ergebnisse" class="level3">
<h3 class="anchored" data-anchor-id="erwartete-ergebnisse">1.3 Erwartete Ergebnisse</h3>
<p>Folgende Erwartungen kamen in der ersten Auseinandersetzung mit dem Datensatz anhand persönlicher Überlegungen auf: * Starke Korrelation des Gehalts mit Erfahrungen * Bekannte/Größere Betriebe zahlen ihren Mitarbeitern mehr * Regionale unterschiede vergelichbar mit BIP * Remote Anteil an der Arbeit hat keinen Einfluss auf das Gehalt * Über die Zeit verdienen Cyber-Security Experten mehr Geld</p>
<p>Innerhalb des Projekts wird versucht Beweise für die aufgestellten Erwartungen zu sammeln, die dafür- oder dagensprechen können.</p>
</section>
</section>
<section id="laden-der-daten-und-entdecken-der-datenstruktur" class="level2">
<h2 class="anchored" data-anchor-id="laden-der-daten-und-entdecken-der-datenstruktur">2. Laden der Daten und entdecken der Datenstruktur</h2>
<p>In diesem Schritt werden die Daten geladen und genauer untersucht. Dabei werden die Daten auf mögliche Fehler überprüft und die Datenstruktur genauer betrachtet. Ziel ist es, wichtige Schritte zu definieren, die im nächsten Schritt für die Aufbereitung der Daten wichtig sind.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Daten laden</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">read_csv</span>(<span class="st">"data/Cyber_salaries.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>data</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,349 × 11
   work_year experience…¹ emplo…² job_t…³ salary salar…⁴ salar…⁵ emplo…⁶ remot…⁷
       &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;   &lt;chr&gt;    &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;
 1      2022 EN           FT      Inform…  68000 EUR       72762 DE          100
 2      2022 SE           FT      Securi… 123400 USD      123400 US            0
 3      2022 SE           FT      Securi…  88100 USD       88100 US            0
 4      2022 SE           FT      Securi… 163575 USD      163575 US          100
 5      2022 SE           FT      Securi… 115800 USD      115800 US          100
 6      2022 MI           FT      Penetr…  40000 EUR       42801 CY          100
 7      2022 SE           FT      Securi… 136600 USD      136600 US          100
 8      2022 SE           FT      Securi… 109280 USD      109280 US          100
 9      2022 SE           FT      Securi… 211600 USD      211600 US          100
10      2022 SE           FT      Securi… 182160 USD      182160 US          100
# … with 1,339 more rows, 2 more variables: company_location &lt;chr&gt;,
#   company_size &lt;chr&gt;, and abbreviated variable names ¹​experience_level,
#   ²​employment_type, ³​job_title, ⁴​salary_currency, ⁵​salary_in_usd,
#   ⁶​employee_residence, ⁷​remote_ratio</code></pre>
</div>
</div>
<section id="übersicht-der-daten" class="level3">
<h3 class="anchored" data-anchor-id="übersicht-der-daten">2.1 Übersicht der Daten</h3>
<p>Daraus folgt, dass die Daten erfolgreich importiert wurden und folgedne Datenstruktur aufweisen:</p>
<table class="table">
<colgroup>
<col style="width: 22%">
<col style="width: 11%">
<col style="width: 34%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Typ</th>
<th>Unique Values</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>work_year</td>
<td>Integer</td>
<td>Zwischen 2020 und 2022</td>
<td>Arbeitsjahr</td>
</tr>
<tr class="even">
<td>experience_level</td>
<td>chr</td>
<td>EN, SE, MI, EX</td>
<td>Erfahrungslevel, wobei EN - Entry level / Junior, MI - Mid level / Intermediate, SE - Senior level / Expert, EX - Executive level / Director</td>
</tr>
<tr class="odd">
<td>employment_type</td>
<td>chr</td>
<td>FT, PT, CT, FL</td>
<td>Art der Anstellung, wobei PT - Part time, FT - Full time, CT - Contract, FL - Freelance</td>
</tr>
<tr class="even">
<td>job_title</td>
<td>chr</td>
<td>Information Security Officer, Security Officer, Security Engineer, Penetration Testing Engineer, Security Analyst, Security Consultant, …</td>
<td>Jobtitel (hier nur die ersten 10 abgebildet)</td>
</tr>
<tr class="odd">
<td>salary</td>
<td>Integer</td>
<td>Zwischen 1740 und 5^{8}</td>
<td>Jahresgehalt</td>
</tr>
<tr class="even">
<td>salary_currency</td>
<td>chr</td>
<td>EUR, USD, GBP, BRL, INR, CAD, CHF, DKK, SGD, AUD, SEK, MXN, ILS, PLN, NOK, IDR, NZD, HUF, ZAR, TWD, RUB</td>
<td>Währung</td>
</tr>
<tr class="odd">
<td>salary_in_usd</td>
<td>Integer</td>
<td>Zwischen 2000 und 8.9992^{5}</td>
<td>Jahresgehalt in USD</td>
</tr>
<tr class="even">
<td>employee_residence</td>
<td>chr</td>
<td>DE, US, CY, BA, GB, CA, IN, FR, ES, BR, BW, TW, NL, AE, CH, DK, CL, SG, AU, IT, PK, GR, GH, AZ, RO, AR, DZ, AF, SI, HR, SE, HU, ET, MX, IL, IE, PL, CR, JP, PT, NG, NO, CZ, ID, EE, KG, KE, BG, IR, NZ, BE, ZA, AT, LU, EG, VN, SA, LT, RU, TR</td>
<td>Wohnort des Mitarbeiters nach Ländercode (ISO 3166)</td>
</tr>
<tr class="odd">
<td>remote_ratio</td>
<td>Integer</td>
<td>Zwischen 0 und 100</td>
<td>Remote Anteil an der Arbeit 0 - Keine Remote Arbeit (weniger als 20%), 50 - Teilweise Remote, 100 - Komplett Remote (mehr als 80%)</td>
</tr>
<tr class="even">
<td>company_location</td>
<td>chr</td>
<td>DE, US, CY, BA, GB, CA, ES, BR, BW, SG, NL, IN, AE, CH, DK, CL, AU, FR, IT, JP, GR, AZ, RO, DZ, AQ, AX, SI, HR, SE, HU, ET, MX, IL, IE, PK, NO, PL, PT, RU, CZ, ID, EE, KE, RS, AR, NZ, BE, ZA, AT, UM, LU, EG, TW, VN, SA, AF, TR</td>
<td>Betriebsstandort nach Ländercode (ISO 3166)</td>
</tr>
<tr class="odd">
<td>company_size</td>
<td>chr</td>
<td>S, M, L</td>
<td>Betriebsgröße, wobei S(small) - Weniger als 50 Angestellte , M(medium) - Zwischen 50 und 250 Angestellte , L(large) - Mehr als 250 Angestellte</td>
</tr>
</tbody>
</table>
<p>Bei genauerer Betrachtung der vorhandenen Daten fällt auf, dass einzelne Variablen, wie z.B. <code>experience_level</code> oder <code>employment_type</code>, als <code>chr</code> definiert sind. Dies ist jedoch nicht korrekt, da diese Variablen als <code>factor</code> definiert sein sollten. Dafür müssen für die einzelnen Variablen Faktoren bzw. geordnete Faktoren angelegt werden. Zusätzlich ist zu beachten, dass die Variablen <code>salary</code> und <code>salary_currency</code> nicht benötigt werden, da diese Informationen bereits in <code>salary_in_usd</code> umgerechnet in US-Dollar enthalten sind. Die Variablen <code>salary</code> und <code>salary_currency</code> sollten daher im nächsten Schritt gelöscht werden. Damit die Daten auch lesbar sind, können die Inhalte der character Felder ausgeschireben werden. So sollten z.B. die Ländernamen nicht mehr nur abgekürzt vorhanden sein, sondern auch in ausgeschriebenem Format.</p>
</section>
<section id="duplikate" class="level3">
<h3 class="anchored" data-anchor-id="duplikate">2.2 Duplikate</h3>
<p>Außerdem muss der Datensatz auf doppelte Einträge überprüft werden. Dazu wird die Funktion <code>duplicated()</code> verwendet, die alle doppelten Einträge zurückgibt. Die Funktion <code>sum()</code> gibt die Anzahl der doppelten Einträge zurück. Die Anzahl der doppelten Einträge sollte mit 0 übereinstimmen. Ist dies nicht der Fall, müssen die doppelten Einträge im nächsten Schritt bereinigt werden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Anzahl der doppelten Einträge</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>duplicate <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">duplicated</span>(data))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Ausgeben der doppelten Einträge</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>data[<span class="fu">duplicated</span>(data),]</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 115 × 11
   work_year experience…¹ emplo…² job_t…³ salary salar…⁴ salar…⁵ emplo…⁶ remot…⁷
       &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;   &lt;chr&gt;    &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;
 1      2022 SE           FT      Securi… 211600 USD      211600 US          100
 2      2022 SE           FT      Securi… 182160 USD      182160 US          100
 3      2022 SE           FT      Securi… 211600 USD      211600 US          100
 4      2022 SE           FT      Securi… 182160 USD      182160 US          100
 5      2022 SE           FT      Penetr… 125000 USD      125000 US          100
 6      2022 SE           FT      Securi… 154700 USD      154700 US          100
 7      2022 SE           FT      Securi… 131495 USD      131495 US          100
 8      2022 SE           FT      Cyber … 137000 USD      137000 US          100
 9      2022 SE           FT      Securi… 228600 USD      228600 US          100
10      2022 SE           FT      Securi… 153600 USD      153600 US          100
# … with 105 more rows, 2 more variables: company_location &lt;chr&gt;,
#   company_size &lt;chr&gt;, and abbreviated variable names ¹​experience_level,
#   ²​employment_type, ³​job_title, ⁴​salary_currency, ⁵​salary_in_usd,
#   ⁶​employee_residence, ⁷​remote_ratio</code></pre>
</div>
</div>
<p>Es sind also 115 doppelte Einträge vorhanden. Die Duplikate können jedoch nich aus dem Datensatz entfernt werden, da es keine eindeutigen Informatioen/Indentifikatoren über die einzelenen Personen gibt und davon ausgegangen werden muss, dass es sich um unterschiedliche Personen des selben Unternhemens handelt mit der selben Bezahlung.</p>
</section>
<section id="fehlende-werte" class="level3">
<h3 class="anchored" data-anchor-id="fehlende-werte">2.3 Fehlende Werte</h3>
<p>Bevor mit dem Bereinigen und umformatieren begonnen werden kann muss überprüft werden, ob die Daten vollständig sind. Dazu wird die Funktion <code>complete.cases()</code> verwendet, die alle Zeilen zurückgibt, die keine fehlenden Werte enthalten. Die Funktion <code>sum()</code> gibt die Anzahl der Zeilen zurück, die keine fehlenden Werte enthalten. Die Anzahl der Zeilen, die keine fehlenden Werte enthalten, sollte mit der Anzahl der Zeilen im Datensatz übereinstimmen. Ist dies nicht der Fall, müssen die fehlenden Werte im nächsten Schritt bereinigt werden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Anzahl der Zeilen ohne fehlende Werte</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">complete.cases</span>(data)) <span class="sc">==</span> <span class="fu">nrow</span>(data)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>Es sind also keine NA’s vorhanden. Damit können die Daten bereinigt werden.</p>
</section>
</section>
<section id="transformieren-und-säubern-der-daten" class="level2">
<h2 class="anchored" data-anchor-id="transformieren-und-säubern-der-daten">3. Transformieren und säubern der Daten</h2>
<p>Aus dem vorherigen Abschnitt folgt, dass verschiedene Faktoren für die einzelnen Spalten angelegt und die Spalten <code>salary</code> und <code>salary_currency</code> gelöscht werden müssen. Zusätzlich werden die Ländernamen in den Spalten <code>employee_residence</code> und <code>company_location</code> ausgeschrieben.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>locations <span class="ot">&lt;-</span> <span class="fu">unique</span>(data<span class="sc">$</span>company_location)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>titles <span class="ot">&lt;-</span> <span class="fu">unique</span>(data<span class="sc">$</span>job_title)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>data_cleaned <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span> <span class="fu">mutate</span>(</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">work_year  =</span> <span class="fu">factor</span>(work_year, <span class="at">levels=</span> <span class="fu">c</span>(<span class="dv">2020</span>,<span class="dv">2021</span>,<span class="dv">2022</span>), <span class="at">ordered =</span> T),</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">experience_level  =</span> <span class="fu">factor</span>(experience_level, <span class="at">levels=</span> <span class="fu">c</span>(<span class="st">'EN'</span>, <span class="st">'MI'</span>, <span class="st">'SE'</span>, <span class="st">'EX'</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'Junior'</span>, <span class="st">'Intermediate'</span>, <span class="st">'Senior'</span>, <span class="st">'Executive'</span>), <span class="at">ordered =</span> T),</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">employment_type  =</span> <span class="fu">factor</span>(employment_type, <span class="at">levels=</span> <span class="fu">c</span>(<span class="st">'PT'</span>, <span class="st">'FT'</span>, <span class="st">'CT'</span>, <span class="st">'FL'</span>), <span class="at">ordered =</span> T),</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">company_size  =</span> <span class="fu">factor</span>(company_size, <span class="at">levels=</span> <span class="fu">c</span>(<span class="st">'S'</span>, <span class="st">'M'</span>, <span class="st">'L'</span>), <span class="at">ordered =</span> T),</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>        <span class="co"># employee_residence = factor(employee_residence, levels = locations),</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>        <span class="co"># company_location = factor(company_location, levels = locations),</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">job_title =</span> <span class="fu">factor</span>(job_title, <span class="at">levels =</span> titles),</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">salary =</span> <span class="cn">NULL</span>,</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">salary_currency =</span> <span class="cn">NULL</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    ) </span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Neue Datenstruktur</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data_cleaned)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [1,349 × 9] (S3: tbl_df/tbl/data.frame)
 $ work_year         : Ord.factor w/ 3 levels "2020"&lt;"2021"&lt;..: 3 3 3 3 3 3 3 3 3 3 ...
 $ experience_level  : Ord.factor w/ 4 levels "Junior"&lt;"Intermediate"&lt;..: 1 3 3 3 3 2 3 3 3 3 ...
 $ employment_type   : Ord.factor w/ 4 levels "PT"&lt;"FT"&lt;"CT"&lt;..: 2 2 2 2 2 2 2 2 2 2 ...
 $ job_title         : Factor w/ 87 levels "Information Security Officer",..: 1 2 2 3 3 4 5 5 3 3 ...
 $ salary_in_usd     : num [1:1349] 72762 123400 88100 163575 115800 ...
 $ employee_residence: chr [1:1349] "DE" "US" "US" "US" ...
 $ remote_ratio      : num [1:1349] 100 0 0 100 100 100 100 100 100 100 ...
 $ company_location  : chr [1:1349] "DE" "US" "US" "US" ...
 $ company_size      : Ord.factor w/ 3 levels "S"&lt;"M"&lt;"L": 1 2 2 2 2 3 2 2 2 2 ...</code></pre>
</div>
</div>
<p>Damit die einzelnen Länder lesbar sind und in einen Zusammenhang mit den Daten gebracht werden kann, werden hier die Länder-Codes durch die Ländernamen ersetzt. Dafür wird der Dataframe <code>ISO_3166_1</code> verwendet, die die Ländercodes und die zugehörigen Ländernamen enthält. Die Ländercodes werden mit den Ländernamen aus dem Dataframe <code>ISO_3166_1</code> ersetzt.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ländernamen hinzufügen</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>data_cleaned <span class="ot">&lt;-</span> data_cleaned <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">full_join</span>(ISO_3166_1[,<span class="fu">c</span>(<span class="st">"Alpha_2"</span>,<span class="st">"Name"</span>)], <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"employee_residence"</span> <span class="ot">=</span> <span class="st">"Alpha_2"</span>), ) <span class="sc">|&gt;</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">full_join</span>(ISO_3166_1[,<span class="fu">c</span>(<span class="st">"Alpha_2"</span>,<span class="st">"Name"</span>)], <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"company_location"</span> <span class="ot">=</span> <span class="st">"Alpha_2"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">employee_residence =</span> Name.x,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">company_location =</span> Name.y,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">Name.x =</span> <span class="cn">NULL</span>,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">Name.y =</span> <span class="cn">NULL</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span> <span class="fu">drop_na</span>() <span class="co"># Löschen von Ländern die keine Verbindung gefunden g</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Neue Datenstruktur</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data_cleaned)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [1,349 × 9] (S3: tbl_df/tbl/data.frame)
 $ work_year         : Ord.factor w/ 3 levels "2020"&lt;"2021"&lt;..: 3 3 3 3 3 3 3 3 3 3 ...
 $ experience_level  : Ord.factor w/ 4 levels "Junior"&lt;"Intermediate"&lt;..: 1 3 3 3 3 2 3 3 3 3 ...
 $ employment_type   : Ord.factor w/ 4 levels "PT"&lt;"FT"&lt;"CT"&lt;..: 2 2 2 2 2 2 2 2 2 2 ...
 $ job_title         : Factor w/ 87 levels "Information Security Officer",..: 1 2 2 3 3 4 5 5 3 3 ...
 $ salary_in_usd     : num [1:1349] 72762 123400 88100 163575 115800 ...
 $ employee_residence: chr [1:1349] "Germany" "United States" "United States" "United States" ...
 $ remote_ratio      : num [1:1349] 100 0 0 100 100 100 100 100 100 100 ...
 $ company_location  : chr [1:1349] "Germany" "United States" "United States" "United States" ...
 $ company_size      : Ord.factor w/ 3 levels "S"&lt;"M"&lt;"L": 1 2 2 2 2 3 2 2 2 2 ...</code></pre>
</div>
</div>
</section>
<section id="auswertungen" class="level2">
<h2 class="anchored" data-anchor-id="auswertungen">4. Auswertungen</h2>
<p>Die Aufbereiteten Daten können nun in diesem Abschnitt ausgewertet werden. Hierfür werden verschiedene Abbildungen und Grafiken generiert, sowie beschrieben.</p>
<section id="betrachtung-von-gehalt-und-erfahrungslevel" class="level3">
<h3 class="anchored" data-anchor-id="betrachtung-von-gehalt-und-erfahrungslevel">4.1 Betrachtung von Gehalt und Erfahrungslevel</h3>
<p>Um einen Einblick zu erhalten, wie viele Daten pro Jahr und Erfahrungslevel vorliegen, wird eine Grafik erstellt, die die Anzahl an Daten pro Jahr darstellt. Hierfür werden die einzelnen Daten pro Jahr und Erfahrungslevel gezählt und in einem Balkendiagramm dargestellt.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="research_cyber_salaries_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Es ist zu sehen, dass über die Zeit mehr Daten erfasst wurden und am meisten Daten von <strong>Senior</strong> und <strong>Intermediate</strong> Mitarbeitern enthalten sind. Die Daten von Executive Mitarbeitern sind dafür am geringsten. Das liegt vermutlich daran, dass es weniger Executive Mitarbeiter gibt und weniger Daten von diesen Mitarbeitern vorliegen.</p>
</section>
<section id="entwicklung-der-gehälter-pro-jahr-und-erfahrungslevel" class="level3">
<h3 class="anchored" data-anchor-id="entwicklung-der-gehälter-pro-jahr-und-erfahrungslevel">4.1.2 Entwicklung der Gehälter pro Jahr und Erfahrungslevel</h3>
<p>Um einen Einblick zu erhalten, wie sich die Gehälter im Laufe der Zeit entwickelt haben, wird eine Grafik erstellt, die die Entwicklung der Gehälter pro Jahr darstellt. Zusätzlich wird nach der Erfahrung gruppiert, um zu sehen, wie sich die Gehälter in Abhängigkeit zur Erfahrung und Jahr entwickelt haben.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="research_cyber_salaries_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In der Grafik ist zu erkennen, dass die Gehälter von <strong>Senior</strong> und <strong>Executives</strong> im Laufe der Zeit gestiegen sind, bei den anderen beiden sind sie ähnlich geblieben. Zusätzlich ist zu erkennen, dass die Gehälter für die Erfahrungslevel <strong>Senior</strong> und <strong>Executives</strong> im Vergleich zu den anderen Erfahrungsleveln deutlich höher sind. Betrachtet man den Boxplot für das Verhältnis wird das auch nochmal deutlich. Zu beachten ist aber, dass die einzelnen Datenpunkte nicht alle gleich verteilt sind, da die Anzahl der Datenpunkte für die einzelnen Erfahrungslevel unterschiedlich ist.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="research_cyber_salaries_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Auch hier ist zu sehen, dass die Gehälter von <strong>Executives</strong> deutlich höher sind. Hier ist aber auch zu sehen, dass die Streuung der Datenpunkte bei den <strong>Executives</strong> am größten ist. Das liegt daran, dass es nur weniger Datenpunkte gibt und die Gehälter von <strong>Executives</strong> sehr unterschiedlich sind (Standardabweichung in 2022: 85380 USD). Bei <strong>Junior</strong> und <strong>Intermediate</strong> Mitarbeitern ist die Streuung der Datenpunkte am geringsten. So liegt das Gehalt im Schnitt wie folgt:</p>
<ul>
<li><strong>Junior Mitarbeiter</strong>: 63727 USD</li>
<li><strong>Intermediate Mitarbeiter</strong>: 102297 USD</li>
<li><strong>Senior Mitarbeiter</strong>: 145937 USD</li>
<li><strong>Executive Mitarbeiter</strong>: 198020 USD</li>
</ul>
</section>
<section id="die-verschiedenen-berufstitel" class="level3">
<h3 class="anchored" data-anchor-id="die-verschiedenen-berufstitel">4.2 Die verschiedenen Berufstitel</h3>
<p>Bei den einzelnen Titeln der Berufe ist es schwer herauszufinden was genau die Bedeutung der Position der einzelenen Person ist, da diese gerne durch das Unternehmen selbst definiert werden. Aufgrunddessen werden in der folgenden Darstellung die einzelen Titel nach Häufigkeit gruppiert und die einzelnen Gruppen in Prozent angegeben. Es werden nur die 15 häufigsten Titel angegeben, alle anderen werden in der Gruppe <code>other</code> zusammengefasst.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 2
   job_title                             n
   &lt;fct&gt;                             &lt;int&gt;
 1 Security Engineer                   247
 2 Cyber Security Analyst              134
 3 Penetration Tester                   77
 4 Information Security Manager         65
 5 Cyber Security Engineer              63
 6 Security Analyst                     53
 7 Information Security Analyst         39
 8 Cyber Security Specialist            31
 9 Information Security Officer         29
10 Cyber Threat Intelligence Analyst    29
# … with 77 more rows</code></pre>
</div>
<div class="cell-output-display">
<p><img src="research_cyber_salaries_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="research_cyber_salaries_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="research_cyber_salaries_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="standort-des-betriebs-tim" class="level1">
<h1>4.4 Standort des Betriebs (Tim)</h1>
</section>
<section id="betriebsgröße-tom" class="level1">
<h1>4.5 Betriebsgröße (Tom)</h1>
<p>Ein weiterer Btrachtungspunkt ist die Betriebsgröße. Wie bereits beschrieben gibt es drei verschiedene Größen: S, M, L. Wobei ein Unternehmen der größe S weniger als 50 Mitarbeiter hat, ein Unternehmen der größe M zwischen 50 und 500 Mitarbeiter hat und ein Unternehmen der größe L mehr als 500 Mitarbeiter hat. Die folgende Grafik zeigt die Verteilung der Betriebsgröße.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="research_cyber_salaries_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Es ist zu sehen, dass überwiegend Mitarbeiter aus große Firmen in diesem Datensatz enthalten sind. Das kann darauf zurückzuführen sein, dass einzelne große Firmen die Daten freigegeben haben, aber mehr Mitarbeiter beschäftigen als kleinere Firmen. Wichitg ist, dass diese Zahl keine Aussage liefert, wie viele verschiedene Unternehmen enthalten sind, sondern dafür wie viele Mitarbeiter aus diesem Datensatz in einem großen, mittleren bzw. kleinen Unternehmen arbeiten.</p>
<p>Als nächstes wird die Verteilung der Gehälter in Abhängigkeit der Betriebsgröße betrachtet. Dazu wird zuerst eine Übersicht über die statistischen Eckdaten für das Verhältnis von Gehältern in Abhängigkeit zur Betriebsgröße und anschließend ein passender Boxplot erstellt.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">company_size</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">S</td>
<td style="text-align: right;">83625.23</td>
<td style="text-align: right;">71653.5</td>
<td style="text-align: right;">47643.34</td>
<td style="text-align: right;">4327</td>
<td style="text-align: right;">240000</td>
</tr>
<tr class="even">
<td style="text-align: left;">M</td>
<td style="text-align: right;">130029.51</td>
<td style="text-align: right;">130200.0</td>
<td style="text-align: right;">55504.45</td>
<td style="text-align: right;">2000</td>
<td style="text-align: right;">300000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">L</td>
<td style="text-align: right;">121093.36</td>
<td style="text-align: right;">107500.0</td>
<td style="text-align: right;">76216.74</td>
<td style="text-align: right;">2000</td>
<td style="text-align: right;">899920</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<p><img src="research_cyber_salaries_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Es fällt auf, dass der Mittelwert der Geählter in mittelgroßen Betrieben höher ist als in großen Betrieben. Das kann darauf zurückzuführen sein, dass in großen Betrieben mehr Mitarbeiter beschäftigt sind, die ein ähnliches Gehalt haben und somit der Mittelwert niedriger ist. Abgesehen davon, ist die Streuung der Gehälter in großen Betrieben größer als in mittelgroßen Betrieben. Hier gibt es einzelne Ausreiser, die ein sehr viel höheres Gehalt haben als die anderen Mitarbeiter. So ist der höchste Wert in großen Betrieben bei 300000 USD und in mittelgroßen Betrieben bei 3e+05 USD. In kleinen Betrieben ist der Mittelwert am geringsten. Er liegt bei 83625 USD und die Streuung ist hier am geringsten.</p>
<p>Es muss nun genauer untersucht werden, ob die Gehälter in Abhängigkeit der Betriebsgröße auch in Abhängigkeit des Erfahrungslevels sind. Dazu wird ein Boxplot erstellt, der die Gehälter in Abhängigkeit der Betriebsgröße und des Erfahrungslevels darstellt.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="research_cyber_salaries_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 18%">
<col style="width: 23%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 8%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">company_size</th>
<th style="text-align: left;">experience_level</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">S</td>
<td style="text-align: left;">Junior</td>
<td style="text-align: right;">55835.94</td>
<td style="text-align: right;">52596.0</td>
<td style="text-align: right;">22780.73</td>
<td style="text-align: right;">4327</td>
<td style="text-align: right;">120000</td>
</tr>
<tr class="even">
<td style="text-align: left;">S</td>
<td style="text-align: left;">Intermediate</td>
<td style="text-align: right;">81552.67</td>
<td style="text-align: right;">78879.0</td>
<td style="text-align: right;">37621.17</td>
<td style="text-align: right;">12005</td>
<td style="text-align: right;">160000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S</td>
<td style="text-align: left;">Senior</td>
<td style="text-align: right;">107022.28</td>
<td style="text-align: right;">90000.0</td>
<td style="text-align: right;">52350.99</td>
<td style="text-align: right;">19445</td>
<td style="text-align: right;">240000</td>
</tr>
<tr class="even">
<td style="text-align: left;">S</td>
<td style="text-align: left;">Executive</td>
<td style="text-align: right;">131556.00</td>
<td style="text-align: right;">117810.0</td>
<td style="text-align: right;">72140.15</td>
<td style="text-align: right;">51389</td>
<td style="text-align: right;">239287</td>
</tr>
<tr class="odd">
<td style="text-align: left;">M</td>
<td style="text-align: left;">Junior</td>
<td style="text-align: right;">62388.78</td>
<td style="text-align: right;">59787.5</td>
<td style="text-align: right;">35065.66</td>
<td style="text-align: right;">2000</td>
<td style="text-align: right;">150000</td>
</tr>
<tr class="even">
<td style="text-align: left;">M</td>
<td style="text-align: left;">Intermediate</td>
<td style="text-align: right;">104670.45</td>
<td style="text-align: right;">101399.0</td>
<td style="text-align: right;">45369.24</td>
<td style="text-align: right;">2056</td>
<td style="text-align: right;">220000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">M</td>
<td style="text-align: left;">Senior</td>
<td style="text-align: right;">152544.03</td>
<td style="text-align: right;">150000.0</td>
<td style="text-align: right;">46468.96</td>
<td style="text-align: right;">27000</td>
<td style="text-align: right;">292000</td>
</tr>
<tr class="even">
<td style="text-align: left;">M</td>
<td style="text-align: left;">Executive</td>
<td style="text-align: right;">156924.69</td>
<td style="text-align: right;">166250.0</td>
<td style="text-align: right;">78806.83</td>
<td style="text-align: right;">15209</td>
<td style="text-align: right;">300000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">L</td>
<td style="text-align: left;">Junior</td>
<td style="text-align: right;">65961.33</td>
<td style="text-align: right;">65500.0</td>
<td style="text-align: right;">31984.63</td>
<td style="text-align: right;">2000</td>
<td style="text-align: right;">200000</td>
</tr>
<tr class="even">
<td style="text-align: left;">L</td>
<td style="text-align: left;">Intermediate</td>
<td style="text-align: right;">102662.07</td>
<td style="text-align: right;">97950.0</td>
<td style="text-align: right;">51087.65</td>
<td style="text-align: right;">2202</td>
<td style="text-align: right;">456621</td>
</tr>
<tr class="odd">
<td style="text-align: left;">L</td>
<td style="text-align: left;">Senior</td>
<td style="text-align: right;">144481.43</td>
<td style="text-align: right;">135000.0</td>
<td style="text-align: right;">79880.41</td>
<td style="text-align: right;">2764</td>
<td style="text-align: right;">899920</td>
</tr>
<tr class="even">
<td style="text-align: left;">L</td>
<td style="text-align: left;">Executive</td>
<td style="text-align: right;">216016.73</td>
<td style="text-align: right;">202000.0</td>
<td style="text-align: right;">94625.60</td>
<td style="text-align: right;">50000</td>
<td style="text-align: right;">600000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Aus dieser Darstellung geht hervor, dass vor allem in großen Betrieben die Gehälter nicht unbedingt bei jedem Mitarbeiter abhängig vom Erfahrungsgrad. So sind die Gehäler von Senior Mitarbeitern im Schnitt zwar niedriger, als die von Executive Mitarbeitern. Dafür sind die Außreiser deutlich höher bei Senior Mitarbeitern.</p>
</section>
<section id="vertragsart-tom" class="level1">
<h1>4.6 Vertragsart (Tom)</h1>
</section>
<section id="remote-vs.-nicht-remote-tim" class="level1">
<h1>4.7 Remote vs.&nbsp;nicht Remote (Tim)</h1>
</section>
<section id="todos" class="level1">
<h1>Todos</h1>
<ul>
<li>Erfahrung gegenüber gehalt (x)</li>
<li>Auftretende Titel mit bezug auf Gehalt (x)</li>
<li>Durschnittliches Gehalt innerhalb der Regionen (Tim)</li>
<li>Timeline über das durchschnittliche Gehalt (x)</li>
<li>Zusammenfassung der Betriebsgröße mit jeweiligen Bezahlungen (Tom)</li>
<li>Zusammenhang gehalt remote vs.&nbsp;nicht remote (Tim)</li>
<li>Vergleich Vertragsart mit Anzahl (Tom)</li>
<li>Jeweils den Text von bisherigen plots ausschreiben (Tim &amp; Tom)</li>
</ul>
<section id="zusammenfassung-und-schlussfolgerung" class="level2">
<h2 class="anchored" data-anchor-id="zusammenfassung-und-schlussfolgerung">Zusammenfassung und Schlussfolgerung</h2>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>